on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        zig:
          - latest
          - master
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ martix.zig }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Fetch Dependencies
        run: zig fetch
      - name: Install Test Dependencies
        run: bun i
      - name: Run Compatibility Test
        run: zig build test-compat
          
